#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP ./matmult 64
#

FILTER='DP MFLOP\|Energy \[J\]\|L2 miss ratio\|L3 bandwidth'

likwid_func(){
    likwid-perfctr -C $1 -o aux.tmp -g $2 -m ./$3 $4 > tempos.tmp
    grep "$FILTER" aux.tmp >> metricas/"$3"_metrics.csv
}

gera_metricas_likwid(){
    for tam in "${TAM_TEST[@]}"; do
        for metrica in "${METRICAS[@]}"; do
            likwid_func $CPU $metrica "$1" $tam
        done
        echo $tam >> metricas/"$1"_tempos.txt
        cat tempos.tmp >> metricas/"$1"_tempos.txt
    done
    rm -f aux.tmp tempos.tmp
}

# TAM_TEST=('64' '100' '128'  '200' '256' '512' '600' '900' '1024' '2000' '2048' '3000' '4000')
TAM_TEST=('64')
METRICAS=('FLOPS_DP' 'L3' 'L2CACHE' 'ENERGY')
CPU=3

make purge 
make
rm -rf metricas
mkdir metricas

echo "performance" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor
gera_metricas_likwid 'matmult'
gera_metricas_likwid 'matmultOTM'
echo "powersave" > /sys/devices/system/cpu/cpufreq/policy${1}/scaling_governor
